*** Variables ***
${TITLE_WOMEN}                    //a[contains(@title,'Women')]
${TITLE_TOPS}                     XPATH=//a[@title='Tops']
${TITLE}                          //a[contains(@title,'T-shirts')]
${TITLE_BLOUSES}                  //a[@title='Blouses']
${TITLE_DRESSES}                  //a[@title='Dresses']
${TITLE_CASUAL_DRESSES}           //a[@title='Casual Dresses']
${TITLE_EVENING}                  //a[@title='Evening Dresses']
${TITLE_SUMMER}                   //a[@title='Summer Dresses']