*** Variables ***
${SIGN_IN}               //a[@class='login'][contains(.,'Sign in')]
${TITULO_PAGINA_LOGIN}   Login - My Store
${EMAIL_CADASTRADO}      christian.hernan@gmail.com
${SENHA_CADASTRADA}      123456
${LOGIN}                 //span[contains(.,'Sign in')]
${TITULO_ACCOUNT}        My account - My Store
${VALIDA_PAGINA_LOGIN}   //h1[@class='page-heading'][contains(.,'Authentication')]
${VALIDA_PAGINA_LOGIN1}  //h3[@class='page-subheading'][contains(.,'Already registered?')]